### PR TITLE
fix: add an option value to the snapshot

### LINKED ISSUE #185: Cannot select <select> option by text
**Describe the bug**
When a <select> element has options like:
<option value="US">United States</option>
The snapshot records only the label (“United States”) instead of the value (“US”). The fill tool then tries to use “United States” as the value, which fails. Puppeteer seems to require the actual value attribute to select the option.

**To Reproduce**
Just try on a native <select> element where the value and text are different.

**Expected behavior**
The fill tool should select the option by value.

**Chrome version:** 140
**Coding agent version:** Cursor 1.4.5
**Model version:** Claude 4.0

**Screenshots**

**Chat log**
N/A

### PR DESCRIPTION
**Pull request by AlinaVarkki**
Fixes #185 

The standard selector value is not included in the AXNode, so add it separately.

### CODE REVIEW

File: src/McpContext.ts [hunk 1]
```diff
@@ -326,19 +330,37 @@ export class McpContext implements Context {
...
         id: `${snapshotId}_${idCounter++}`,
-        children: node.children
-          ? node.children.map(child => assignIds(child))
-          : [],
+        children: [],
       };
+
+      // The AXNode for an option doesn't contain its `value`.
+      // Therefore, set text content of the option as value.
+      if (node.role === 'option') {
```
Comment (OrKoN) [inline src/McpContext.ts:344]: is there a reason why we cannot use the node.name? I really do not want use to have evals when building snapshots. If we cannot do it without evals, we need to fix it in the chromium code.

File: src/McpContext.ts [hunk 2]
```diff
@@ -326,19 +330,33 @@ export class McpContext implements Context {
     // will be used for the tree serialization and mapping ids back to nodes.
     let idCounter = 0;
     const idToNode = new Map<string, TextSnapshotNode>();
-    const assignIds = (node: SerializedAXNode): TextSnapshotNode => {
+    const assignIds = async (
```
Comment (OrKoN) [inline src/McpContext.ts]: this does not need to be async now, let's change it back to sync and revert other changes related to making it async.

File: src/McpContext.ts [hunk 3]
```diff
@@ -334,11 +338,21 @@ export class McpContext implements Context {
...
+          nodeWithId.value = optionText.toString();
+        }
+      }
+
       idToNode.set(nodeWithId.id, nodeWithId);
       return nodeWithId;
     };
 
-    const rootNodeWithId = assignIds(rootNode);
+    const rootNodeWithId = await assignIds(rootNode);
```
Comment (OrKoN) [inline src/McpContext.ts]:
```suggestion
    const rootNodeWithId = assignIds(rootNode);
```
